package model;
// Generated Jul 5, 2018 8:12:02 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable {

	private int iditem;
	private String name;
	private Float cost;
	private Set orderses = new HashSet(0);

	public Item() {
	}

	public Item(int iditem) {
		this.iditem = iditem;
	}

	public Item(int iditem, String name, Float cost, Set orderses) {
		this.iditem = iditem;
		this.name = name;
		this.cost = cost;
		this.orderses = orderses;
	}

	public int getIditem() {
		return this.iditem;
	}

	public void setIditem(int iditem) {
		this.iditem = iditem;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getCost() {
		return this.cost;
	}

	public void setCost(Float cost) {
		this.cost = cost;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
