package model;
// Generated Jul 5, 2018 8:12:02 AM by Hibernate Tools 3.5.0.Final

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int idorders;
	private Item item;
	private Customer customer;
	private Integer quantity;
	private String description;

	public Orders() {
	}

	public Orders(int idorders) {
		this.idorders = idorders;
	}

	public Orders(int idorders, Item item, Customer customer, Integer quantity, String description) {
		this.idorders = idorders;
		this.item = item;
		this.customer = customer;
		this.quantity = quantity;
		this.description = description;
	}

	public int getIdorders() {
		return this.idorders;
	}

	public void setIdorders(int idorders) {
		this.idorders = idorders;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
